In [1]:
import torch
import numpy as np
from game import Connect4
from mcts import MCTS
from network import ConnectNet, AlphaLoss
from arena import Arena
from players import random_play

In [2]:
from self_play_learning import SelfPlay

In [12]:
game = Connect4()

In [6]:
net = ConnectNet()

In [7]:
net.state_dict()

OrderedDict([('conv.conv1.weight', tensor([[[[ 0.1478, -0.0966, -0.1187],
                        [-0.0710,  0.0354,  0.0092],
                        [ 0.0127,  0.3229, -0.0177]]],
              
              
                      [[[-0.2092, -0.2878, -0.1131],
                        [ 0.1684, -0.2200,  0.2575],
                        [-0.0829,  0.1744, -0.0659]]],
              
              
                      [[[ 0.2167, -0.2382,  0.3286],
                        [-0.3188, -0.1321,  0.2124],
                        [-0.2007,  0.0635, -0.0958]]],
              
              
                      ...,
              
              
                      [[[ 0.1691, -0.1672,  0.0522],
                        [-0.2025, -0.1745, -0.2872],
                        [-0.0385,  0.2383, -0.2652]]],
              
              
                      [[[ 0.1617, -0.1996, -0.3217],
                        [-0.1209,  0.1828, -0.2485],
                        [-0.0604, -0.2568,  0.0165]]

In [8]:
net.load_state_dict(torch.load("results/best_net.pth", map_location='cpu'))

In [10]:
net.state_dict()

OrderedDict([('conv.conv1.weight', tensor([[[[ 0.3510,  0.2877,  0.3399],
                        [-0.4400, -0.2920,  0.1948],
                        [-0.1039, -0.1347,  0.0947]]],
              
              
                      [[[ 0.2687,  0.1941,  0.3731],
                        [-0.3580,  0.2338,  0.2118],
                        [-0.0865, -0.1177, -0.0341]]],
              
              
                      [[[-0.1943, -0.0021,  0.3048],
                        [ 0.0238,  0.0600,  0.1627],
                        [ 0.1433,  0.2130,  0.4807]]],
              
              
                      ...,
              
              
                      [[[ 0.1240,  0.4298,  0.1700],
                        [ 0.1145,  0.1279,  0.2076],
                        [ 0.1887, -0.0373,  0.2499]]],
              
              
                      [[[ 0.1641, -0.0888, -0.0413],
                        [ 0.3569, -0.1852,  0.3131],
                        [-0.4724, -0.3756,  0.1897]]

In [14]:
args = {"tempThreshold":15,
        "num_iterations":30,
        "num_episodes":100,
        "max_train_examples_history":200000,
        "batch_size":64,
        "n_challenges":40,
        "update_threshold":0.5,
        "save_path": "results/",
        "n_sim":25,
        "exploration_constant":1.,
        "device":"cpu",
        "n_epochs":10,
        }
mcts = MCTS(game, net, args)

### Train the NN

In [15]:
coach = SelfPlay(game, net, args)

In [17]:
coach.learn()

  0%|          | 0/100 [00:00<?, ?it/s]

Iteration 1
Getting experience...


100%|██████████| 100/100 [03:22<00:00,  1.92s/it]


Start training...
loss epoch: 2.954900475648733
loss epoch: 2.928229432839614
loss epoch: 2.9226101361788235
loss epoch: 2.903245311516982
loss epoch: 2.867548245650071
loss epoch: 2.851105836721567
loss epoch: 2.8504469119585476
loss epoch: 2.8203635124059825
loss epoch: 2.7911734672693105


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.7688773687069235
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.625
Not trained net wins 15 times, Trained net wins 25, 0 draws.
Iteration 1 Model accepted !
Iteration 2
Getting experience...


100%|██████████| 100/100 [03:10<00:00,  2.37s/it]


Start training...
loss epoch: 2.9466444604537068
loss epoch: 2.927670955657959
loss epoch: 2.9166011296066583
loss epoch: 2.905687911837709
loss epoch: 2.88998522010504
loss epoch: 2.877292852775723
loss epoch: 2.856009422564039
loss epoch: 2.840552905026604
loss epoch: 2.824534818237903


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.8089785529117957
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.8205128205128205
Not trained net wins 7 times, Trained net wins 32, 1 draws.
Iteration 2 Model accepted !
Iteration 3
Getting experience...


100%|██████████| 100/100 [03:13<00:00,  1.55s/it]


Start training...
loss epoch: 2.941227684149871
loss epoch: 2.9241390131615304
loss epoch: 2.9145276836446814
loss epoch: 2.9041009754747957
loss epoch: 2.893373453939283
loss epoch: 2.8809433756647884
loss epoch: 2.86026588323954
loss epoch: 2.8369644654763713
loss epoch: 2.8240853548049927


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.7951285355799906
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.625
Not trained net wins 15 times, Trained net wins 25, 0 draws.
Iteration 3 Model accepted !
Iteration 4
Getting experience...


100%|██████████| 100/100 [03:26<00:00,  1.73s/it]


Start training...
loss epoch: 2.9461243369362573
loss epoch: 2.925812851298939
loss epoch: 2.9121538316360627
loss epoch: 2.9035750976716628
loss epoch: 2.883119898613053
loss epoch: 2.853848006990221
loss epoch: 2.831944039373687
loss epoch: 2.8101544645097523
loss epoch: 2.787392255031701


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.76307558531713
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.325
Not trained net wins 27 times, Trained net wins 13, 0 draws.
Iteration 5
Getting experience...


100%|██████████| 100/100 [03:43<00:00,  2.19s/it]


Start training...
loss epoch: 2.7712451312690973
loss epoch: 2.728034995496273
loss epoch: 2.693248590454459
loss epoch: 2.664394773542881
loss epoch: 2.632628398016095
loss epoch: 2.6044042967259884
loss epoch: 2.5697369119152427
loss epoch: 2.5383538212627172
loss epoch: 2.4933758340775967


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.4295956352725625
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.925
Not trained net wins 3 times, Trained net wins 37, 0 draws.
Iteration 5 Model accepted !
Iteration 6
Getting experience...


100%|██████████| 100/100 [04:02<00:00,  2.18s/it]


Start training...
loss epoch: 2.7546833320787756
loss epoch: 2.7037478465183526
loss epoch: 2.6703460748028602
loss epoch: 2.6396306958168174
loss epoch: 2.6122186502833276
loss epoch: 2.58116307987529
loss epoch: 2.555027437817519
loss epoch: 2.52210118968016
loss epoch: 2.4746198608617114


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.4264046553593532
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.7
Not trained net wins 12 times, Trained net wins 28, 0 draws.
Iteration 6 Model accepted !
Iteration 7
Getting experience...


100%|██████████| 100/100 [04:04<00:00,  2.85s/it]


Start training...
loss epoch: 2.733458610291177
loss epoch: 2.6792877354520432
loss epoch: 2.6441234971614596
loss epoch: 2.609053112090902
loss epoch: 2.566971291886999
loss epoch: 2.5216409640109285
loss epoch: 2.4812641093071472
loss epoch: 2.4416108816228013
loss epoch: 2.391863108949458


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.342838627226809
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.725
Not trained net wins 11 times, Trained net wins 29, 0 draws.
Iteration 7 Model accepted !
Iteration 8
Getting experience...


100%|██████████| 100/100 [04:10<00:00,  2.20s/it]


Start training...
loss epoch: 2.7128786357966335
loss epoch: 2.656007624756206
loss epoch: 2.6179409016262403
loss epoch: 2.5790823882276364
loss epoch: 2.5347794819961895
loss epoch: 2.4874288401820444
loss epoch: 2.4452697547999294
loss epoch: 2.3896096641367133
loss epoch: 2.3314344666220923


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.251869476925243
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.6410256410256411
Not trained net wins 14 times, Trained net wins 25, 1 draws.
Iteration 8 Model accepted !
Iteration 9
Getting experience...


100%|██████████| 100/100 [04:01<00:00,  2.30s/it]


Start training...
loss epoch: 2.6999105558395384
loss epoch: 2.643800352096558
loss epoch: 2.6109369440078734
loss epoch: 2.5822666015625
loss epoch: 2.5524897012710572
loss epoch: 2.518666976928711
loss epoch: 2.4807405395507813
loss epoch: 2.427267000198364
loss epoch: 2.376162929058075


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.3231102542877196
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.5897435897435898
Not trained net wins 16 times, Trained net wins 23, 1 draws.
Iteration 9 Model accepted !
Iteration 10
Getting experience...


100%|██████████| 100/100 [04:04<00:00,  2.36s/it]


Start training...
loss epoch: 2.6890135651381413
loss epoch: 2.633735413653146
loss epoch: 2.5904122718288383
loss epoch: 2.5517391810637777
loss epoch: 2.5057900794036025
loss epoch: 2.4534408422551546
loss epoch: 2.3912532632885455
loss epoch: 2.3314651569013494
loss epoch: 2.2647158864129904


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.1709193017373516
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.5945945945945946
Not trained net wins 15 times, Trained net wins 22, 3 draws.
Iteration 10 Model accepted !
Iteration 11
Getting experience...


100%|██████████| 100/100 [04:10<00:00,  2.87s/it]


Start training...
loss epoch: 2.6766018821642947
loss epoch: 2.6154771600014124
loss epoch: 2.5766614247591066
loss epoch: 2.5346047442692976
loss epoch: 2.4912647207578025
loss epoch: 2.4365068398989163
loss epoch: 2.3746799513315544
loss epoch: 2.2985028204245443
loss epoch: 2.211607495561624


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.1034627797511907
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.631578947368421
Not trained net wins 14 times, Trained net wins 24, 2 draws.
Iteration 11 Model accepted !
Iteration 12
Getting experience...


100%|██████████| 100/100 [04:35<00:00,  1.89s/it]


Start training...
loss epoch: 2.667742492142603
loss epoch: 2.6098128498802953
loss epoch: 2.578869674666127
loss epoch: 2.5489673882465196
loss epoch: 2.516338512602045
loss epoch: 2.473935829802961
loss epoch: 2.4254153839792916
loss epoch: 2.369335637999543
loss epoch: 2.303931425559074


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.2268241798499817
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.6578947368421053
Not trained net wins 13 times, Trained net wins 25, 2 draws.
Iteration 12 Model accepted !
Iteration 13
Getting experience...


100%|██████████| 100/100 [04:22<00:00,  1.46s/it]


Start training...
loss epoch: 2.6605513580241746
loss epoch: 2.5978020495663845
loss epoch: 2.555424915454633
loss epoch: 2.5034925270835453
loss epoch: 2.434976439991853
loss epoch: 2.3343595760164284
loss epoch: 2.2015003667343263
loss epoch: 2.084058774178135
loss epoch: 1.9885851289477385


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.916006896615343
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.625
Not trained net wins 15 times, Trained net wins 25, 0 draws.
Iteration 13 Model accepted !
Iteration 14
Getting experience...


100%|██████████| 100/100 [04:10<00:00,  3.06s/it]


Start training...
loss epoch: 2.6540818156265633
loss epoch: 2.5966863986922473
loss epoch: 2.5597909026029635
loss epoch: 2.5198073800017196
loss epoch: 2.4707888074037507
loss epoch: 2.4147460489738277
loss epoch: 2.3427195758354373
loss epoch: 2.25109349285684
loss epoch: 2.1298016155638346


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 2.023112748018125
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.6923076923076923
Not trained net wins 12 times, Trained net wins 27, 1 draws.
Iteration 14 Model accepted !
Iteration 15
Getting experience...


100%|██████████| 100/100 [04:22<00:00,  2.62s/it]


Start training...
loss epoch: 2.6462150369834037
loss epoch: 2.5889469757338994
loss epoch: 2.553994999212377
loss epoch: 2.5103755973582893
loss epoch: 2.4569900909700007
loss epoch: 2.392324134774877
loss epoch: 2.3154199374207542
loss epoch: 2.2146714095076825
loss epoch: 2.0820526825896217


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.9676600149853736
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.4444444444444444
Not trained net wins 20 times, Trained net wins 16, 4 draws.
Iteration 16
Getting experience...


100%|██████████| 100/100 [05:09<00:00,  2.76s/it]


Start training...
loss epoch: 2.052982091406981
loss epoch: 1.9045361494024595
loss epoch: 1.814824675520261
loss epoch: 1.739939591040214
loss epoch: 1.6887581591804823
loss epoch: 1.6360768248637518
loss epoch: 1.5964320768912634
loss epoch: 1.5687752867738405
loss epoch: 1.5489522352814675


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.5066710477073988
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.65
Not trained net wins 14 times, Trained net wins 26, 0 draws.
Iteration 16 Model accepted !
Iteration 17
Getting experience...


100%|██████████| 100/100 [04:52<00:00,  2.58s/it]


Start training...
loss epoch: 2.0581543820575603
loss epoch: 1.9115698772726708
loss epoch: 1.821354107254917
loss epoch: 1.7508733902162719
loss epoch: 1.6878490598456373
loss epoch: 1.6397873903941182
loss epoch: 1.5954740040510604
loss epoch: 1.558151207618343
loss epoch: 1.5351747468837256


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.523135580136938
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.4358974358974359
Not trained net wins 22 times, Trained net wins 17, 1 draws.
Iteration 18
Getting experience...


100%|██████████| 100/100 [04:39<00:00,  3.97s/it]


Start training...
loss epoch: 1.7420013425566934
loss epoch: 1.5969576967846264
loss epoch: 1.5384274877201427
loss epoch: 1.5016876409270548
loss epoch: 1.4762462186813354
loss epoch: 1.4593242128328843
loss epoch: 1.4423267091404308
loss epoch: 1.4256258875673467
loss epoch: 1.4272861261801286


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.4118849809603258
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.575
Not trained net wins 17 times, Trained net wins 23, 0 draws.
Iteration 18 Model accepted !
Iteration 19
Getting experience...


100%|██████████| 100/100 [04:25<00:00,  2.74s/it]


Start training...
loss epoch: 1.8195184802518292
loss epoch: 1.637351853156376
loss epoch: 1.5503202629743678
loss epoch: 1.5105675352580756
loss epoch: 1.4724419321449502
loss epoch: 1.4674256418417904
loss epoch: 1.4385786410261387
loss epoch: 1.4319007995811581
loss epoch: 1.4061619658821851


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.4093460619551854
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.23076923076923078
Not trained net wins 30 times, Trained net wins 9, 1 draws.
Iteration 20
Getting experience...


100%|██████████| 100/100 [04:43<00:00,  2.27s/it]


Start training...
loss epoch: 1.5876409916669083
loss epoch: 1.459891361490834
loss epoch: 1.4180233801203377
loss epoch: 1.392215204393458
loss epoch: 1.3830532818984367
loss epoch: 1.3783374144733436
loss epoch: 1.3677404833960571
loss epoch: 1.3725036587475572
loss epoch: 1.35552606909163


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.3413666329275653
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.6923076923076923
Not trained net wins 12 times, Trained net wins 27, 1 draws.
Iteration 20 Model accepted !
Iteration 21
Getting experience...


100%|██████████| 100/100 [04:59<00:00,  2.65s/it]


Start training...
loss epoch: 1.6809866681740553
loss epoch: 1.4997040171871128
loss epoch: 1.441473768027186
loss epoch: 1.4035485693074148
loss epoch: 1.395757952961353
loss epoch: 1.37559063345285
loss epoch: 1.3689228476734336
loss epoch: 1.3543777540553965
loss epoch: 1.3658190331327806


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.3365773000848402
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.6923076923076923
Not trained net wins 12 times, Trained net wins 27, 1 draws.
Iteration 21 Model accepted !
Iteration 22
Getting experience...


100%|██████████| 100/100 [05:10<00:00,  2.33s/it]


Start training...
loss epoch: 1.7165659145812768
loss epoch: 1.5105949929683884
loss epoch: 1.4401617681532237
loss epoch: 1.4178552199478094
loss epoch: 1.3822831485657334
loss epoch: 1.3709818584726037
loss epoch: 1.3569084563524048
loss epoch: 1.3536218418551318
loss epoch: 1.3260510509586059


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.3344723576238389
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.775
Not trained net wins 9 times, Trained net wins 31, 0 draws.
Iteration 22 Model accepted !
Iteration 23
Getting experience...


100%|██████████| 100/100 [05:04<00:00,  3.04s/it]


Start training...
loss epoch: 1.73064217708268
loss epoch: 1.5215301834619963
loss epoch: 1.4398527620257913
loss epoch: 1.407385520882659
loss epoch: 1.3932869253414017
loss epoch: 1.3564834656132447
loss epoch: 1.352582033928279
loss epoch: 1.3356794279355269
loss epoch: 1.3341234933871489


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.3250863426825503
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.75
Not trained net wins 10 times, Trained net wins 30, 0 draws.
Iteration 23 Model accepted !
Iteration 24
Getting experience...


100%|██████████| 100/100 [04:26<00:00,  2.75s/it]


Start training...
loss epoch: 1.7574079671137905
loss epoch: 1.5397260627671392
loss epoch: 1.457823844369545
loss epoch: 1.4089164408058437
loss epoch: 1.3939418656440665
loss epoch: 1.3577483765555745
loss epoch: 1.3430939394290438
loss epoch: 1.331176680349959
loss epoch: 1.3371849508072482


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.3287269818485175
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.525
Not trained net wins 19 times, Trained net wins 21, 0 draws.
Iteration 24 Model accepted !
Iteration 25
Getting experience...


100%|██████████| 100/100 [04:19<00:00,  2.57s/it]


Start training...
loss epoch: 1.7777425444592143
loss epoch: 1.54623079089469
loss epoch: 1.459470071678354
loss epoch: 1.4093802614139879
loss epoch: 1.3791839684844769
loss epoch: 1.3679614527829809
loss epoch: 1.351942010665451
loss epoch: 1.3408313903201272
loss epoch: 1.3228276093850972


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.3127596860124364
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.5789473684210527
Not trained net wins 16 times, Trained net wins 22, 2 draws.
Iteration 25 Model accepted !
Iteration 26
Getting experience...


100%|██████████| 100/100 [04:38<00:00,  2.26s/it]


Start training...
loss epoch: 1.79881436288573
loss epoch: 1.5545242448239402
loss epoch: 1.4605915230736046
loss epoch: 1.4230789645263044
loss epoch: 1.3916438134722726
loss epoch: 1.3561458139350366
loss epoch: 1.3440076977627164
loss epoch: 1.3276148810352062
loss epoch: 1.3141903386438916


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.3167395300559583
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.6153846153846154
Not trained net wins 15 times, Trained net wins 24, 1 draws.
Iteration 26 Model accepted !
Iteration 27
Getting experience...


100%|██████████| 100/100 [04:51<00:00,  2.86s/it]


Start training...
loss epoch: 1.8012428510230496
loss epoch: 1.5626947157352575
loss epoch: 1.4575630972725215
loss epoch: 1.4144000450401704
loss epoch: 1.3854207187234873
loss epoch: 1.355195917577622
loss epoch: 1.3360947490014732
loss epoch: 1.3143567427008618
loss epoch: 1.305052059343212


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.298022576928277
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.65
Not trained net wins 14 times, Trained net wins 26, 0 draws.
Iteration 27 Model accepted !
Iteration 28
Getting experience...


100%|██████████| 100/100 [04:50<00:00,  3.19s/it]


Start training...
loss epoch: 1.811736504856356
loss epoch: 1.559394824080053
loss epoch: 1.4649624649294235
loss epoch: 1.4094971419708235
loss epoch: 1.3627339618110443
loss epoch: 1.3461301658626124
loss epoch: 1.3325841794566216
loss epoch: 1.321463676829115
loss epoch: 1.2943386679768296


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.2906064399764905
Start evaluation...


  0%|          | 0/100 [00:00<?, ?it/s]

pourcentage trained wins :  0.55
Not trained net wins 18 times, Trained net wins 22, 0 draws.
Iteration 28 Model accepted !
Iteration 29
Getting experience...


100%|██████████| 100/100 [04:44<00:00,  2.47s/it]


Start training...
loss epoch: 1.8197434531147456
loss epoch: 1.5638924087103285
loss epoch: 1.46490150913676
loss epoch: 1.4053558421032732
loss epoch: 1.3715342906127022
loss epoch: 1.3395945577376143
loss epoch: 1.3358017764546353
loss epoch: 1.3126132444808976
loss epoch: 1.2975357998989019


  0%|          | 0/20 [00:00<?, ?it/s]

loss epoch: 1.2867275211972056
Start evaluation...


100%|██████████| 20/20 [02:22<00:00,  6.41s/it]

pourcentage trained wins :  0.45
Not trained net wins 22 times, Trained net wins 18, 0 draws.


### Play with the agent

In [23]:
def human_player(board):
    valid_actions = np.where(board[0,:] == 0)[0]
    done = False
    while not done:
        inp = int(input())
        if inp in valid_actions:
            done = True
            return inp
        else:
            print('Invalid action, try again')

In [28]:
human_player(game.init_state)

9
Invalid action


KeyboardInterrupt: 

In [25]:
arena = Arena(lambda x: np.argmax(mcts.run_sims(x)), human_player, game)

In [27]:
arena.play_game(verbose=True)

Turn  1 Previous action  None Player  1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
None
Turn  2 Previous action  3 Player  -1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
None
2
Turn  3 Previous action  2 Player  1
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0.  0.  0.]]
None
Turn  4 Previous action  1 Player  -1
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  1.  0.  0.  0.]]
None
3
Turn  5 Previous action  3 Player  1
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.

-1.0